FROM php:7.1-alpine

MAINTAINER Jakub Zalas <jakub@zalas.pl>

ENV COMPOSER_ALLOW_SUPERUSER 1
ENV BUILD_DEPS="autoconf file g++ gcc libc-dev make pkgconf re2c unzip"
ENV LIB_DEPS="zlib-dev"
ENV TOOL_DEPS="git graphviz"
ENV PATH="$PATH:/root/.composer/vendor/bin:/root/QualityAnalyzer/bin:/root/DesignPatternDetector/bin"
ENV TOOLS_JSON=/root/tools.json

ADD tools.json ${TOOLS_JSON}
ADD tools.php /usr/local/bin/tools.php

RUN apk add --no-cache --virtual .tool-deps $TOOL_DEPS $LIB_DEPS \
 && apk add --no-cache --virtual .build-deps $BUILD_DEPS \
 && git clone https://github.com/nikic/php-ast.git && cd php-ast && phpize && ./configure && make && make install && cd .. && rm -rf php-ast && docker-php-ext-enable ast \
 && docker-php-ext-install zip \
 && echo "date.timezone=Europe/London" >> $PHP_INI_DIR/php.ini \
 && echo "memory_limit=-1" >> $PHP_INI_DIR/php.ini \
 && echo "phar.readonly=0" >> $PHP_INI_DIR/php.ini \
 && php /usr/local/bin/tools.php install \
 && apk del .build-deps

CMD php /usr/local/bin/tools.php list
