name: Release

on:
    schedule:
        -   cron: '0 3 * * 1'
    workflow_dispatch:

jobs:
    release:
        runs-on: ubuntu-latest
        name: Release
        steps:
            -   uses: actions/checkout@v4
            -   run: git config user.email 'jakub@zalas.pl' && git config user.name 'Jakub Zalas'
            -   run: make auto-release
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
