name: Update toolbox

on:
    schedule:
        -   cron: '30 1 * * *'

jobs:
    nightly-builds:
        runs-on: ubuntu-latest
        name: Update
        steps:
            -   uses: actions/checkout@v4
            -   run: git config user.email 'jakub@zalas.pl' && git config user.name 'Jakub Zalas'
            -   run: sudo apt-get update && sudo apt-get install -y hub
            -   run: make update-toolbox-pr
                env:
                    GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
